import React, { useState } from 'react';
import { ArrowRight, ArrowUpRight, Check, CircleNotch, EnvelopeSimple, Heart, Images, MapPin, NotePencil } from '@phosphor-icons/react';
import { api, Modal } from './shared.jsx';

export function Gallery({ photos }) {
  const [filter, setFilter] = useState('Tất cả'), [selected, setSelected] = useState(null);
  const categories = ['Tất cả', ...new Set(photos.map(p => p.category))];
  return <><section className="page-intro"><div className="eyebrow"><Images size={15} /> THE LITTLE SCRAPBOOK</div><h1>Giữ lại <span>một chút dịu dàng.</span></h1><p>Vài khung hình, vài câu chuyện. Những điều nhỏ mình muốn nhớ lâu.</p></section><div className="mood-tabs centered">{categories.map(c => <button aria-pressed={filter === c} className={filter === c ? 'selected' : ''} onClick={() => setFilter(c)} key={c}>{c}</button>)}</div><div className="photo-grid">{photos.filter(p => filter === 'Tất cả' || p.category === filter).map(photo => <button className="polaroid" onClick={() => setSelected(photo)} key={photo.id}><span className="tape" /><img src={photo.image} alt={photo.title} loading="lazy" /><div className="photo-meta"><span>{new Date(photo.date).toLocaleDateString('vi-VN')}</span><span><MapPin size={12} /> {photo.location}</span></div><h2>{photo.title}</h2><p>{photo.caption}</p>{photo.owner && <span className="photo-open">Chia sẻ bởi {photo.owner}</span>}<span className="photo-open">Mở kỷ niệm <ArrowUpRight size={15} /></span></button>)}</div>{!photos.length && <div className="empty-state"><Images size={36} /><p>Những kỷ niệm đầu tiên sắp được thêm vào.</p></div>}<div className="closing-note"><span /><p>Collecting moments, not things.</p><span /></div>{selected && <Modal title={selected.title} onClose={() => setSelected(null)} className="photo-modal"><img className="lightbox-image" src={selected.image} alt={selected.title} /><div className="photo-detail"><span className="eyebrow">{selected.category} · {new Date(selected.date).toLocaleDateString('vi-VN')}</span><p>{selected.caption}</p><span className="muted"><MapPin size={15} /> {selected.location}</span></div></Modal>}</>;
}

export function Guestbook({ settings = {} }) {
  const [sending, setSending] = useState(false), [success, setSuccess] = useState(false), [error, setError] = useState('');
  async function send(event) { event.preventDefault(); setSending(true); setError(''); const form = new FormData(event.currentTarget); try { await api('/api/messages', { method: 'POST', body: JSON.stringify(Object.fromEntries(form)) }); setSuccess(true); } catch (e) { setError(e.message); } finally { setSending(false); } }
  return <><section className="page-intro"><div className="eyebrow"><NotePencil size={15} /> THE GUESTBOOK</div><h1>Một lời chào, <span>một niềm vui.</span></h1><p>Một bài hát bạn thích, một ký ức vừa ghé qua, hay đơn giản là “xin chào”.</p></section><section className="guest-layout"><aside className="guest-note"><span className="eyebrow">FROM MELODIK, WITH LOVE</span><h2>Rất vui vì bạn ở đây.</h2><p>Melodik là một góc nhỏ cho âm nhạc và những điều bình dị. Mỗi lời nhắn đều khiến nơi này ấm áp hơn một chút.</p><img src={settings.guestbookImage || '/artwork/coffee.webp'} alt="Ảnh lời nhắn" /><div className="handwritten">Cứ viết như gửi một người bạn.</div><span className="small-note"><Heart size={15} /> Đây là lời nhắn riêng cho quản trị viên. <a href="/community">Kết bạn và chat ở Góc cộng đồng.</a></span></aside><div className="letter-form">{success ? <div className="success-state"><span className="success-icon"><Check size={30} /></span><h2>Đã nhận được lời nhắn!</h2><p>Cảm ơn bạn đã để lại một chút ấm áp ở đây.</p><button className="button secondary" onClick={() => setSuccess(false)}>Viết thêm một lời nhắn</button></div> : <form onSubmit={send}><div className="eyebrow">A LITTLE NOTE</div><h2>Bạn muốn kể điều gì?</h2><label>Tên của bạn <span>*</span><input name="name" required maxLength={80} placeholder="Mình là…" autoComplete="name" /></label><label>Email <span>*</span><input type="email" name="email" required maxLength={254} placeholder="ban@example.com" autoComplete="email" /></label><label>Lời nhắn <span>*</span><textarea name="message" required minLength={1} maxLength={3000} rows={5} placeholder="Hôm nay mình đã nghe một bản nhạc thật hay…" /></label>{error && <p role="alert" className="form-error">{error}</p>}<button className="button primary wide" disabled={sending}>{sending ? <CircleNotch className="spin" size={18} /> : <EnvelopeSimple size={18} />}{sending ? 'Đang gửi…' : 'Gửi một chút yêu thương'}<ArrowRight size={17} /></button><p className="form-footnote">Email dùng để phản hồi lời nhắn, không hiển thị công khai.</p></form>}</div></section></>;
}
